wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 80:80
  volumes:
    - .:/var/www/html/wp-content/themes/BeXcellent-2

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: 12345
